# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField()),
                ('on_time', models.TimeField()),
                ('off_time', models.TimeField()),
                ('set_temp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(verbose_name='Time of reading')),
                ('temperature', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heating.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField()),
                ('heating_on', models.BooleanField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heating.Zone')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heating.Zone'),
        ),
    ]
